Update Release_5719303J_Jenkinsfile

diff --git a/Release_5719303J_Jenkinsfile b/Release_5719303J_Jenkinsfile
--- a/Release_5719303J_Jenkinsfile
+++ b/Release_5719303J_Jenkinsfile
@@ -1,67 +1,93 @@
-pipeline {
-    agent any
+agent {
+    node {
+        label 'master'
+    }
+}
 
-    stages {
-        stage('S1_5719303J') {
-            steps {
-                echo "Stage1_5719303J : Release Environment Preparation Completed"
+tools { 
+    maven 'maven3' 
+}
+
+options {
+    buildDiscarder logRotator( 
+                daysToKeepStr: '15', 
+                numToKeepStr: '10'
+        )
+}
+
+environment {
+    APP_NAME = "STUDENT_APP"
+    APP_ENV  = "DEV"
+}
+
+stages {
+    
+    stage('Stage1') {
+        steps {
+            sh """
+            echo "Stage1_5719303j : Release Environment Preparation Completed"
+            """
+        }
+    }
+
+    stage('Stage2') {
+        steps {
+            sh """
+            docker stop webapp_5719303j || true
+            docker rm webapp_5719303j || true
+            docker run -d --name webapp_5719303j -p 31200:80 wb1_image_5719303j
+            echo "Stage2_5719303j : Release Container webapp_5719303j Created Completed"
+            """
+        }
+    }
+
+    stage('Stage3') {
+        parallel {
+            stage('API Test') {
+                steps {
+                    sh """
+                    echo "Stage3_5719303j: API Test Completed"
+                    """
+                }
+            }
+            stage('Scan Test') {
+                steps {
+                    sh """
+                    echo "Stage3_5719303j: Scan Test Completed"
+                    """
+                }
             }
         }
-        
-        
-        stage('S2_5719303J') {
-            steps {
-                script {
-                    def imageName = 'wb1_image_5719303j' 
-                    def containerName = 'webapp_5719303j' 
+    }
 
-                    sh "docker stop ${containerName}"
-                    sh "docker rm ${containerName}"
-
-                    sh "docker run -d --name ${containerName} -p 31200:80 ${imageName}"
-                }
-            }
-      }
-        
-        stage('S3_5719303J') {
-            parallel {
-                stage('S3 API Test') {
-                    steps {
-                        echo "Stage3_5719303J: API Test Completed"
-                    }
-                }
-                stage('S3 Scan Test') {
-                    steps {
-                        echo "Stage3_5719303J: Scan Test Completed"
-                    }
-                }
+    stage('Stage4') {
+        steps {
+            script {
+                def userInput = input(
+                    message: "5719303j, proceed to release the work to next phase?",
+                    ok: "Proceed",
+                    parameters: [
+                        [$class: 'BooleanParameterDefinition', defaultValue: false, description: '', name: 'Abort']
+                    ]
+                )
+               
             }
         }
-        
-        stage('S4_5719303J') {
-            steps {
-                script {
-                    s4Input = input(id: 'S4Input', message: '5719303J, proceed to release the work to next phase?', parameters: [booleanParam(defaultValue: true, description: 'Click Proceed or Abort', name: 'Proceed')])
-                    if (s4Input) {
-                        env.DECISION = 'proceed'
+    }
+
+
+stage('Stage5') {
+        when {
+            expression {
+                return env.STAGE_NAME == 'Stage5'
+            }
+        }
+        steps {
+            if (userInput.Release == 'Proceed') {
+                        echo "Stage5_5719303j : Work Release – Proceeds to Next Phase"
                     } else {
-                        env.DECISION = 'abort'
+                        echo "Stage5_5719303j : Work Release - Stops"
                     }
-                }
-            }
-        }
-        
-        stage('S5_5719303J') {
-            steps {
-                script {
-                    if (env.DECISION == 'proceed') {
-                        echo "Stage5_5719303J : Work Release – Proceeds to Next Phase"
-                    } else {
-                        echo "Stage5_5719303J : Work Release - Stops"
-                        currentBuild.result = 'ABORTED'
-                    }
-                }
-            }
         }
     }
 }
